method: bayes
metric:
  goal: maximize
  name: phon_acc
command:
  - ${env}
  - ${interpreter}
  - scripts/sweep.py
  - configs/config.cfg
  - training
  - --code
  - scripts/phonologizer.py
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  components.tok2vec.model.width:
    values:
      - 96
      - 128
      - 300
  components.tok2vec.model.depth:
    values:
      - 4
      - 6
      - 8
  components.tok2vec.model.embed_size:
    values:
      - 2000
      - 6000
      - 10000
  training.dropout:
    distribution: uniform
    min: 0.05
    max: 0.5
  training.optimizer.learn_rate:
    distribution: uniform
    min: 0.001
    max: 0.01
